In [142]:
#Q.1
import pandas as pd
sales = pd.Series([120,150,180,210])
print(sales)

0    120
1    150
2    180
3    210
dtype: int64

In [143]:
#Q.2
marks = pd.Series([72,81,69,90])
print(marks)
marks.values

0    72
1    81
2    69
3    90
dtype: int64

array([72, 81, 69, 90])

In [144]:
#Q.3
print(marks)
marks.index

0    72
1    81
2    69
3    90
dtype: int64

RangeIndex(start=0, stop=4, step=1)

In [145]:
#Q.4
temp = pd.Series([28,31,30,29],index=["Mon","Tue","Wed","Thu"])
print(temp)

Mon    28
Tue    31
Wed    30
Thu    29
dtype: int64

In [146]:
#Q.5
population = pd.Series([35,42,31],index=["Delhi","Mumbai","Jaipur"])
print(population)
population["Jaipur"]

Delhi     35
Mumbai    42
Jaipur    31
dtype: int64

np.int64(31)

In [147]:
#Q.6
Score = pd.Series([35,68,44,79,52])
Score[Score>50]

1    68
3    79
4    52
dtype: int64

In [148]:
#Q.7
subjects = pd.Series([76,83,91],index=["Physics","Chemistry","Maths"])
print(subjects)
"Chemistry" in subjects.index

Physics      76
Chemistry    83
Maths        91
dtype: int64

True

In [149]:
#Q.8
BFF = pd.Series([8,20,57],index=["Anjali","Janvi","Vanshika"])
BFF.to_dict()

{'Anjali': 8, 'Janvi': 20, 'Vanshika': 57}

In [150]:
#Q.9
prices = {'Pen': 10,'Notebook': 55,'Bag': 700}
s = pd.Series(prices)
print(s)
print(type(prices))

Pen          10
Notebook     55
Bag         700
dtype: int64
<class 'dict'>

In [151]:
#Q.10
P1 = {'A': 10,'B': 55,'C': 700}
s = pd.Series(P1)
print(s.index)

Index(['A', 'B', 'C'], dtype='object')

In [152]:
#Q.11
data = {'A': 10,'B': 20,'C': 30}
s = pd.Series(data,index=['A','B','C','D'])
print(s)

A    10.0
B    20.0
C    30.0
D     NaN
dtype: float64

In [153]:
#Q.12
s = pd.Series([1,2,3,4],index=['a','b','c','d'])
print(s.isnull())

a    False
b    False
c    False
d    False
dtype: bool

In [154]:
#Q.13
s = pd.Series([1,2,3,4],index=['a','b','c','d'])
print(s.notnull())

a    True
b    True
c    True
d    True
dtype: bool

In [155]:
#Q.14
sales = pd.Series([120,150,180,210])
sales.name = "Monthky Sales"
print(sales)

0    120
1    150
2    180
3    210
Name: Monthky Sales, dtype: int64

In [156]:
#Q.15
sales = pd.Series([120,150,180,210])
sales.index.name = "Month"
print(sales)

Month
0    120
1    150
2    180
3    210
dtype: int64

In [157]:
#Q.16
s = pd.Series([18, 45, 27, 61], index=['P','Q','R','S'])
print(s[s > 30])

Q    45
S    61
dtype: int64

In [158]:
#Q.17
s = pd.Series([500, 600, 700], index=['East','West','North'])
print('West' in s)
print(500 in s)

True
False

In [159]:
#Q.18
city_data = {'Delhi': 80, 'Pune': 65, 'Kochi': 70}
s=pd.Series(city_data,index=['Delhi','Kochi','Pune','Chennai'])
print(s)

Delhi      80.0
Kochi      70.0
Pune       65.0
Chennai     NaN
dtype: float64

In [160]:
#Q.19
s = pd.Series({'W': 5, 'X': 10, 'Y': 15}, index=['W','X','Y','Z'])
pd.isnull(s)

W    False
X    False
Y    False
Z     True
dtype: bool

In [161]:
#Q.20
s = pd.Series({'W': 5, 'X': 10, 'Y': 15}, index=['W','X','Y','Z'])
pd.notnull(s)

W     True
X     True
Y     True
Z    False
dtype: bool

In [162]:
#Q.21
s1 = pd.Series([10, 20, 30], index=['A','B','C'])
s2 = pd.Series([1, 2, 3], index=['C','A','B'])
s1 + s2

A    12
B    23
C    31
dtype: int64

In [163]:
#Q.22
s1 = pd.Series({'A': 12, 'B': 18})
s2 = pd.Series({'B': 5, 'C': 9})
s1 + s2

A     NaN
B    23.0
C     NaN
dtype: float64

In [164]:
#Q.23
stock = pd.Series([25, 40, 18], index=['Item1','Item2','Item3'])
stock_dict = stock.to_dict()
stock2 = pd.Series(stock_dict)
stock_dict
stock2

Item1    25
Item2    40
Item3    18
dtype: int64

In [165]:
#Q.24
marks = {'Maths': 88, 'Science': 74, 'English': 69, 'History': 81}
s = pd.Series(marks)
s[s > 70]

Maths      88
Science    74
History    81
dtype: int64

In [166]:
#Q.25
rev = pd.Series([10000, 15000, 20000],index=['Delhi', 'Pune', 'Kochi'])
rev.name = "Revenue"
rev.index.name = "Branch"
print(rev)

Branch
Delhi    10000
Pune     15000
Kochi    20000
Name: Revenue, dtype: int64

In [167]:
#Q.26
north = pd.Series({'Jan': 40, 'Feb': 55, 'Mar': 60})
south = pd.Series({'Feb': 20, 'Mar': 25, 'Apr': 30})
total = north + south
print(total)

Apr     NaN
Feb    75.0
Jan     NaN
Mar    85.0
dtype: float64

In [168]:
#Q.27
d = {'Red': 12, 'Blue': 18, 'Green': 24}
labels = ['Green','Red','Yellow','Blue']
result = pd.Series(d, index=labels)
print(result)
print(pd.isnull(result))

Green     24.0
Red       12.0
Yellow     NaN
Blue      18.0
dtype: float64
Green     False
Red       False
Yellow     True
Blue      False
dtype: bool

In [169]:
#Q.28
s = pd.Series([90, 75, 82], index=['Ravi','Aman','Neha'])
d = s.to_dict()
s2 = pd.Series(d)
print(s)
print(s2)

Ravi    90
Aman    75
Neha    82
dtype: int64
Ravi    90
Aman    75
Neha    82
dtype: int64

In [174]:
#Q.29
sales = pd.Series(
    [450, 750, 600, 350],
    index=['Pen', 'Laptop', 'Printer', 'Mouse']
)
print(sales.values)
print(sales.index)
print(sales['Laptop'])
print(sales[sales>500])
print('Pen' in sales)
s = sales.to_dict()
print(s)

[450 750 600 350]
Index(['Pen', 'Laptop', 'Printer', 'Mouse'], dtype='object')
750
Laptop     750
Printer    600
dtype: int64
True
{'Pen': 450, 'Laptop': 750, 'Printer': 600, 'Mouse': 350}

In [175]:
#Q.30
data = {'A': 15, 'B': 35, 'C': 25}
s = pd.Series(data, index=['C','A','D','B'])
s.name = 'Observations'
s.index.name = 'Category'
print(s)
print(pd.notnull(s))
print(s[s>20])
print(s.name)
print(s.index.name)

Category
C    25.0
A    15.0
D     NaN
B    35.0
Name: Observations, dtype: float64
Category
C     True
A     True
D    False
B     True
Name: Observations, dtype: bool
Category
C    25.0
B    35.0
Name: Observations, dtype: float64
Observations
Category